version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: leads_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/leads_db
    volumes:
      - ./app:/app/app

volumes:
  postgres_data: